name: Tauri Build with AutoFix

on:
  workflow_dispatch:
  
env:
  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
  TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

jobs:
  build-windows:
    name: Build Windows x64
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: 'npm'

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true

      - name: AutoFix Code Issues
        shell: pwsh
        run: |
          npm install -D eslint @typescript-eslint/eslint-plugin @typescript-eslint/parser
          
          # 使用单行JSON格式避免YAML解析问题
          if (!(Test-Path .eslintrc.js)) {
            $config = '{ "extends": ["plugin:@typescript-eslint/recommended"], "rules": { "@typescript-eslint/no-unused-vars": ["warn", { "argsIgnorePattern": "^_", "varsIgnorePattern": "^_" }] } }'
            $config | ConvertFrom-Json | ConvertTo-Json -Depth 10 | Out-File .eslintrc.js
          }

          npx eslint src --ext .vue,.ts --fix --quiet
          if ($LASTEXITCODE -ne 0) { Write-Output "⚠️ 自动修复完成（可能存在需要手动处理的问题）" }
          
          if (Test-Path "src/views/Dashboard/Index.vue") {
            Rename-Item "src/views/Dashboard/Index.vue" "index.vue"
          }

      - name: Install Dependencies
        run: npm ci

      - name: Build Frontend
        run: npm run build

      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli

      - name: Build Tauri App
        run: npm run tauri build -- --target x86_64-pc-windows-msvc

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Build
          path: |
            src-tauri/target/x86_64-pc-windows-msvc/release/*.exe
            src-tauri/target/x86_64-pc-windows-msvc/release/bundle/msi/*.msi
