name: Tauri Cross-Platform Build

on:
  workflow_dispatch:

env:
  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
  TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: Windows
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: macOS
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: Linux

    runs-on: ${{ matrix.os }}
    name: Build ${{ matrix.artifact_name }}

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Install pnpm explicitly
      - name: Install pnpm
        run: |
          npm install -g pnpm@8
          echo "PNPM_PATH=$(which pnpm)" >> $GITHUB_ENV
          echo "$(which pnpm)" >> $GITHUB_PATH

      # 3. Setup Node.js (without auto pnpm install)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      # 4. Verify installation
      - name: Verify pnpm
        run: |
          pnpm -v
          which pnpm
          echo "PATH: $PATH"

      # 5. Install Rust
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      # 6. Platform-specific dependencies
      - name: Install system dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y libwebkit2gtk-4.0-dev libssl-dev libgtk-3-dev
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install create-dmg
          fi

      # 7. Cache dependencies
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      # 8. Install project dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 9. Build frontend
      - name: Build frontend
        run: pnpm run build

      # 10. Build Tauri
      - name: Build Tauri
        run: pnpm tauri build --target ${{ matrix.target }}

      # 11. Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}-Build
          path: |
            src-tauri/target/${{ matrix.target }}/release/
          retention-days: 7
