name: Tauri Build with AutoFix

on:
  workflow_dispatch:
  
env:
  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
  TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

jobs:
  build-windows:
    name: Build Windows x64
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: 'npm'

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true

      - name: AutoFix Code Issues
        shell: pwsh
        run: |
          # 安装修复工具
          npm install -D eslint @typescript-eslint/eslint-plugin @typescript-eslint/parser

          # 创建临时ESLint配置（修正后的Here-String语法）
          if (!(Test-Path .eslintrc.js)) {
            @"
            module.exports = {
              extends: ['plugin:@typescript-eslint/recommended'],
              rules: {
                '@typescript-eslint/no-unused-vars': ['warn', { 
                  argsIgnorePattern: '^_',
                  varsIgnorePattern: '^_' 
                }]
              }
            }
            "@ | Out-File -FilePath .eslintrc.js -Encoding utf8
          }

          # 执行自动修复
          npx eslint src --ext .vue,.ts --fix --quiet || echo "自动修复完成"

          # 修复文件名大小写
          if (Test-Path "src/views/Dashboard/Index.vue") {
            Rename-Item "src/views/Dashboard/Index.vue" "index.vue"
          }

      - name: Install Dependencies
        run: npm ci

      - name: Build Frontend
        run: npm run build

      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli

      - name: Build Tauri App
        run: npm run tauri build -- --target x86_64-pc-windows-msvc

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Build
          path: |
            src-tauri/target/x86_64-pc-windows-msvc/release/*.exe
            src-tauri/target/x86_64-pc-windows-msvc/release/bundle/msi/*.msi
