name: Tauri Build with AutoFix

on:
  workflow_dispatch:
  
env:
  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
  TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

jobs:
  build-windows:
    name: Build Windows x64
    runs-on: windows-latest

    steps:
      # 1. 检出代码
      - uses: actions/checkout@v4

      # 2. 设置 Node.js 22
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: 'npm'

      # 3. 安装 Rust 工具链
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true

      # 4. 核心修复步骤（已修复 Here-String 问题）
      - name: AutoFix Code Issues
        shell: pwsh
        run: |
          # 安装必要的修复工具
          npm install -D eslint @typescript-eslint/eslint-plugin @typescript-eslint/parser

          # 更安全的 ESLint 配置生成方式
          if (!(Test-Path .eslintrc.js)) {
            $eslintConfig = @'
module.exports = {
  extends: ['plugin:@typescript-eslint/recommended'],
  rules: {
    '@typescript-eslint/no-unused-vars': ['warn', { 
      argsIgnorePattern: '^_',
      varsIgnorePattern: '^_' 
    }]
  }
}
'@
            $eslintConfig | Out-File -FilePath .eslintrc.js -Encoding utf8
          }

          # 执行自动修复（非阻塞模式）
          try {
            npx eslint src --ext .vue,.ts --fix --quiet
            Write-Output "✅ 自动修复完成"
          } catch {
            Write-Output "⚠️ 自动修复完成（可能存在需要手动处理的问题）"
          }

          # 处理文件名大小写问题
          if (Test-Path "src/views/Dashboard/Index.vue") {
            Rename-Item "src/views/Dashboard/Index.vue" "index.vue"
            Write-Output "✅ 已修复文件名大小写问题"
          }

      # 5. 安装项目依赖
      - name: Install Dependencies
        run: npm ci

      # 6. 构建前端
      - name: Build Frontend
        run: npm run build

      # 7. 安装 Tauri CLI
      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli

      # 8. 构建 Tauri 应用
      - name: Build Tauri App
        run: npm run tauri build -- --target x86_64-pc-windows-msvc

      # 9. 上传制品
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Build
          path: |
            src-tauri/target/x86_64-pc-windows-msvc/release/*.exe
            src-tauri/target/x86_64-pc-windows-msvc/release/bundle/msi/*.msi
