name: Tauri Cross-Platform Build

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
  TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
  NODE_OPTIONS: "--max-old-space-size=8192"

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: Windows
            shell_cmd: pwsh
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: macOS
            shell_cmd: bash
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: Linux
            shell_cmd: bash

    timeout-minutes: 90
    runs-on: ${{ matrix.os }}
    name: Build ${{ matrix.artifact_name }}

    steps:
      # 1. 安全检出代码
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: false

      # 2. 设置Node.js环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: 'pnpm'

      # 3. 初始化pnpm（跨平台兼容方案）
      - name: Initialize pnpm
        run: |
          npm install -g corepack
          corepack enable
          corepack prepare pnpm@latest --activate
          echo "PNPM_VERSION=$(pnpm -v)" >> $GITHUB_ENV
        shell: ${{ matrix.shell_cmd }}

      # 4. 平台特定设置
      - name: Platform setup
        run: |
          case "$RUNNER_OS" in
            "Linux")
              sudo apt-get update -y
              sudo apt-get install -y \
                libwebkit2gtk-4.1-dev \
                libgtk-3-dev \
                libayatana-appindicator3-dev \
                librsvg2-dev \
                libssl-dev \
                libasound2-dev \
                patchelf
              ;;
            "macOS")
              ulimit -S -n 65536
              brew update-reset
              brew install create-dmg || true
              ;;
            "Windows")
              choco install -y llvm --no-progress --force || true
              ;;
          esac
        shell: ${{ matrix.shell_cmd }}

      # 5. 安装Rust工具链
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
          components: rust-src, clippy, rustfmt

      # 6. 智能缓存配置
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            ~/.pnpm-store
            node_modules
            target
          key: ${{ runner.os }}-${{ matrix.target }}-${{ hashFiles('pnpm-lock.yaml') }}

      # 7. 安装项目依赖
      - name: Install dependencies
        run: |
          pnpm config set store-dir ~/.pnpm-store
          pnpm install --frozen-lockfile --shamefully-hoist
        shell: ${{ matrix.shell_cmd }}

      # 8. 构建前端
      - name: Build frontend
        run: pnpm run build
        shell: ${{ matrix.shell_cmd }}

      # 9. 构建Tauri应用
      - name: Build Tauri
        timeout-minutes: 45
        env:
          RUST_BACKTRACE: full
        run: |
          pnpm tauri build --target ${{ matrix.target }} --verbose 2>&1 | tee build.log
          find src-tauri/target -name "*.log" -exec cp {} . \;
        shell: ${{ matrix.shell_cmd }}

      # 10. 上传制品
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}_Build_${{ github.run_number }}
          path: |
            src-tauri/target/${{ matrix.target }}/release/
            *.log
