name: Build Installers

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Select platform to build'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - macos
          - linux
          - windows

jobs:
  build-macos:
    if: ${{ github.event.inputs.platform == 'all' || github.event.inputs.platform == 'macos' }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build Tauri
        run: pnpm run tauri build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-dmg
          path: src-tauri/target/release/bundle/dmg/*.dmg
      - name: 打包绿色版 zip
        run: |
          cd src-tauri/target/release
          7z a LingYunFrp-Tauri-Client-macos-portable.zip LingYunFrp-Tauri-Client.app
      - name: 上传绿色版 zip
        uses: actions/upload-artifact@v4
        with:
          name: macos-portable-zip
          path: src-tauri/target/release/LingYunFrp-Tauri-Client-macos-portable.zip

  build-linux:
    if: ${{ github.event.inputs.platform == 'all' || github.event.inputs.platform == 'linux' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libglib2.0-dev \
            libsoup-3.0-dev \
            pkg-config \
            libwebkit2gtk-4.1-dev \
            libjavascriptcoregtk-4.1-dev \
            libssl-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build Tauri
        run: pnpm run tauri build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-deb
          path: |
            src-tauri/target/release/bundle/deb/*.deb
            src-tauri/target/release/bundle/appimage/*.AppImage
      - name: 打包绿色版 zip
        run: |
          cd src-tauri/target/release
          7z a LingYunFrp-Tauri-Client-linux-portable.zip LingYunFrp-Tauri-Client
      - name: 上传绿色版 zip
        uses: actions/upload-artifact@v4
        with:
          name: linux-portable-zip
          path: src-tauri/target/release/LingYunFrp-Tauri-Client-linux-portable.zip

  build-windows:
    if: ${{ github.event.inputs.platform == 'all' || github.event.inputs.platform == 'windows' }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build Tauri
        run: pnpm run tauri build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-msi
          path: |
            src-tauri/target/release/bundle/msi/*.msi
            src-tauri/target/release/bundle/nsis/*.exe
      - name: 打包绿色版 zip
        run: |
          cd src-tauri/target/release
          7z a LingYunFrp-Tauri-Client-windows-portable.zip LingYunFrp-Tauri-Client.exe
      - name: 上传绿色版 zip
        uses: actions/upload-artifact@v4
        with:
          name: windows-portable-zip
          path: src-tauri/target/release/LingYunFrp-Tauri-Client-windows-portable.zip
