name: Tauri Cross-Platform Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
  TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: Windows
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: macOS
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: Linux

    runs-on: ${{ matrix.os }}
    name: Build ${{ matrix.artifact_name }}

    steps:
      # 1. 检出代码
      - uses: actions/checkout@v4

      # 2. 显式安装 pnpm (关键修复)
      - name: Install pnpm
        run: |
          npm install -g pnpm@8
          echo "PNPM_PATH=$(which pnpm)" >> $GITHUB_ENV
          echo "$(which pnpm)" >> $GITHUB_PATH

      # 3. 设置 Node.js (不自动安装 pnpm)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'pnpm'

      # 4. 验证 pnpm 安装
      - name: Verify pnpm
        run: |
          pnpm -v
          which pnpm
          echo "PATH: $PATH"

      # 5. 安装 Rust
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      # 6. 平台特定依赖
      - name: Install system dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y libwebkit2gtk-4.0-dev libssl-dev libgtk-3-dev
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install create-dmg
          fi

      # 7. 缓存配置
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('pn
